title: 'Eric Teo'
og_image: /assets/img/header.png
header:
  pages:
    - name: Home
      slug: /
    - name: Blog
    - name: About

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: zcteo.cn@gmail.com
      link: mailto:zcteo.cn@gmail.com
    - name: WeChat
      value: EricTeo-
      link: "#"
  follow:
    - name: GitHub
      link: https://github.com/zcteo
    - name: WeiBo
      link: https://weibo.com/u/6664803739
    - name: Twitter
      link: https://twitter.com/zcteo
      username: "@zcteo"
    - name: Facebook
      link: https://facebook.com/zcteo

# 评论系统
valine:
  enable: true
  leanCloud_app_id: 'o84Egzh8KNWz67spySSU3xln-gzGzoHsz'
  leanCloud_app_key: 'o2VCxaUgT8sO4FDDN4fyeoV9'
  placeholder: '欢迎提出您的宝贵意见'

# 访问分析系统
analytics:
  google:
    enable: false
    value: 'G-H9X9BNEKZG'
  baidu:
    enable: true
    value: '774e787dc731c8f79c3249dbb9280504'
