title: 'Eric Teo'
og_image: /assets/img/header.png
header:
  pages:
    - name: Home
      slug: /
    - name: Blog
    - name: About

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: zcteo.cn@gmail.com
      link: mailto:zcteo.cn@gmail.com
    - name: WeChat
      value: EricTeo-
      link: "#"
  follow:
    - name: GitHub
      link: https://github.com/zcteo
    - name: WeiBo
      link: https://weibo.com/u/6664803739

valine:
  enable: true
  leanCloud_app_id: 'o84Egzh8KNWz67spySSU3xln-gzGzoHsz'
  leanCloud_app_key: 'o2VCxaUgT8sO4FDDN4fyeoV9'
  placeholder: '欢迎提出您的宝贵意见'
