name: Blog Generator

# 触发时机
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5

      - name: Gen Locale
        run: sudo locale-gen en_US.UTF-8

      - name: Install
        run: |
          gem install bundler -v 2.0.2
          bundle install

      - name: Build
        working-directory: ./scripts
        run: ./build.sh

      - name: Commit and Push
        working-directory: ./_site
        run: |
          git config --global user.name EricTeo
          git config --global user.email zcteo.cn@gmail.com
          git config --global core.autocrlf input
          git init
          git checkout -b master
          git add .
          git commit -m 'init'
          git push "https://zcteo:${{secrets.TOKEN}}@github.com/zcteo/zcteo.github.io" HEAD:master -f -q
