name: Action Build Pages

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5

      - name: Generate locale
        run: sudo locale-gen en_US.UTF-8

      - name: Install
        run: |
          export MAKEFLAGS="-j$(nproc)"
          bundle install

      - name: Build
        working-directory: ./scripts
        run: ./build.sh

      - name: Config git
        run: |
          git config --global user.name EricTeo
          git config --global user.email zcteo.cn@gmail.com
          git config --global core.autocrlf input

      - name: Push to zcteo.github.io
        working-directory: ./_site
        run: |
          git init
          git add .
          git commit -m 'Initial commit'
          git push "https://zcteo:${{secrets.TOKEN}}@github.com/zcteo/zcteo.github.io" HEAD:pages -f -q

      - name: Push to github-pages
        working-directory: ./_site
        run: |
          rm -rf .git
          echo 'zcteo.cn' >CNAME
          git init
          git add .
          git commit -m 'Initial commit'
          git push "https://zcteo:${{secrets.TOKEN}}@github.com/zcteo/github-pages" HEAD:pages -f -q
